"""Generates the pixel art of the Platformer sample (no dependencies).

    python tools/make_art.py      (from samples/Platformer)

Every image is drawn from code with a small palette and gets a 1-pixel dark
outline, so the art can be tweaked (or regenerated by an agent) by editing
this file. Output: assets/sprites/*.png
"""
import math
import os
import struct
import zlib

PALETTE = {
    "k": (29, 27, 42),      # outline
    "r": (224, 64, 64), "R": (164, 36, 52),
    "s": (247, 196, 145), "S": (214, 150, 104),
    "b": (59, 111, 216), "B": (38, 70, 150),
    "w": (255, 255, 255), "W": (205, 220, 235),
    "y": (255, 214, 64), "Y": (222, 150, 30), "o": (255, 240, 170),
    "g": (96, 196, 82), "G": (48, 132, 64), "h": (150, 226, 110),
    "d": (160, 104, 60), "D": (112, 70, 42), "l": (196, 140, 88),
    "n": (150, 156, 170), "N": (96, 100, 116), "m": (190, 196, 206),
    "p": (240, 120, 170), "c": (120, 180, 255), "C": (80, 130, 220),
    "t": (122, 84, 52), "T": (84, 56, 36),
}


class Canvas:
    def __init__(self, w, h):
        self.w, self.h = w, h
        self.px = [[None] * w for _ in range(h)]

    def set(self, x, y, c):
        if 0 <= x < self.w and 0 <= y < self.h:
            self.px[y][x] = c

    def rect(self, x, y, w, h, c):
        for yy in range(y, y + h):
            for xx in range(x, x + w):
                self.set(xx, yy, c)

    def blit(self, other, ox, oy):
        for y in range(other.h):
            for x in range(other.w):
                if other.px[y][x] is not None:
                    self.set(ox + x, oy + y, other.px[y][x])

    def outline(self, c="k"):
        src = [row[:] for row in self.px]
        for y in range(self.h):
            for x in range(self.w):
                if src[y][x] is not None:
                    continue
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < self.w and 0 <= ny < self.h and src[ny][nx] not in (None, c):
                        self.px[y][x] = c
                        break
        return self

    def save(self, path):
        raw = bytearray()
        for row in self.px:
            raw.append(0)
            for c in row:
                raw.extend(bytes(PALETTE[c] + (255,)) if c else b"\x00\x00\x00\x00")
        raw = bytes(raw)
        def chunk(tag, data):
            return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", self.w, self.h, 8, 6, 0, 0, 0))
        png += chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.write(png)


def sheet(frames, columns):
    w, h = frames[0].w, frames[0].h
    rows = (len(frames) + columns - 1) // columns
    out = Canvas(w * columns, h * rows)
    for i, f in enumerate(frames):
        out.blit(f, (i % columns) * w, (i // columns) * h)
    return out


def rnd(seed):
    """Tiny deterministic generator (same art on every machine)."""
    state = [seed * 2654435761 % 4294967296 or 1]
    def next_int(n):
        state[0] = (state[0] * 1103515245 + 12345) % 2147483648
        return state[0] % n
    return next_int


# ----- Player: 16x16, faces right. Frames: idle x2, run x4, jump, fall, hurt -----
def hero(legs, arm, bob=0, eyes_closed=False, hurt=False):
    c = Canvas(16, 16)
    y = 1 + bob
    c.rect(5, y + 1, 6, 1, "r")                 # cap
    c.rect(4, y + 2, 8, 2, "r")
    c.rect(10, y + 3, 3, 1, "R")                # brim
    c.rect(5, y + 4, 6, 4, "s")                 # face
    c.rect(4, y + 5, 1, 2, "s")                 # ear side
    if hurt:
        c.set(8, y + 5, "k"); c.set(10, y + 5, "k")
    elif not eyes_closed:
        c.set(9, y + 5, "k")
    c.set(10, y + 7, "S")
    c.rect(5, y + 8, 6, 3, "b")                 # shirt
    c.rect(6, y + 8, 4, 1, "B")
    ax, ay = arm
    c.rect(ax, y + 8 + ay, 2, 2, "s")           # hand
    c.rect(5, y + 11, 6, 1, "B")                # belt
    for (lx, ly, lh) in legs:                   # legs: x, y offset, height
        c.rect(lx, y + 12 + ly, 2, lh, "d")
        c.rect(lx - (1 if lx < 8 else 0), y + 12 + ly + lh, 3, 1, "D")  # shoe
    return c.outline()

player_frames = [
    hero([(5, 0, 2), (9, 0, 2)], (11, 0)),
    hero([(5, 0, 2), (9, 0, 2)], (11, 0), bob=1, eyes_closed=True),
    hero([(4, 0, 2), (10, -1, 2)], (3, 0)),
    hero([(6, 0, 2), (8, 0, 2)], (11, 0), bob=1),
    hero([(9, 0, 2), (4, -1, 2)], (11, 1)),
    hero([(7, 0, 2), (8, 0, 2)], (3, 1), bob=1),
    hero([(4, -1, 2), (10, -2, 2)], (11, -3)),  # jump
    hero([(5, 0, 2), (9, -1, 2)], (12, -2)),    # fall
    hero([(5, 0, 2), (9, 0, 2)], (12, -3), hurt=True),
]

# ----- Tiles 16x16 (8 columns x 2 rows) --------------------------------------------
def dirt(seed):
    t = Canvas(16, 16)
    t.rect(0, 0, 16, 16, "d")
    r = rnd(seed)
    for _ in range(14):
        t.set(r(16), r(16), "D" if r(3) else "l")
    return t

def grass_top():
    t = dirt(1)
    t.rect(0, 0, 16, 4, "g")
    for x in range(16):
        t.set(x, 4 + (1 if x % 5 in (1, 2) else 0), "G")
        if x % 4 == 0:
            t.set(x, 0, "h")
    return t

def brick():
    t = Canvas(16, 16)
    t.rect(0, 0, 16, 16, "n")
    for y in (3, 7, 11, 15):
        t.rect(0, y, 16, 1, "N")
    for i, y in enumerate((0, 4, 8, 12)):
        off = 4 if i % 2 else 0
        for x in (off, off + 8):
            t.rect(x % 16, y, 1, 3, "N")
        t.rect(1 + off, y, 2, 1, "m")
    return t

def plank():
    t = Canvas(16, 16)
    t.rect(0, 0, 16, 16, "t")
    for y in (0, 5, 10):
        t.rect(0, y, 16, 1, "l")
        t.rect(0, y + 4, 16, 1, "T")
    for x, y in ((3, 2), (12, 7), (6, 12)):
        t.set(x, y, "T")
    return t

def spikes():
    t = Canvas(16, 16)
    for i in range(4):
        x0 = i * 4
        for h in range(7):
            w = max(1, (7 - h) // 2)
            t.rect(x0 + 2 - w // 2, 15 - h, w if w > 1 else 1, 1, "m" if h > 4 else "n")
    t.rect(0, 15, 16, 1, "N")
    return t

def bonus(used=False):
    t = Canvas(16, 16)
    t.rect(0, 0, 16, 16, "Y" if not used else "D")
    t.rect(1, 1, 14, 14, "y" if not used else "d")
    for x, y in ((2, 2), (13, 2), (2, 13), (13, 13)):
        t.set(x, y, "Y" if not used else "D")
    if not used:
        q = ["..kkkk..", ".kk..kk.", "......kk", "....kkk.", "....kk..", "........", "....kk..", "....kk.."]
        for yy, row in enumerate(q):
            for xx, ch in enumerate(row):
                if ch == "k":
                    t.set(4 + xx, 4 + yy, "Y")
    return t

def bush():
    t = Canvas(16, 16)
    for cx, cy, r in ((5, 11, 4), (10, 10, 5), (13, 12, 3)):
        for y in range(16):
            for x in range(16):
                if (x - cx) ** 2 + (y - cy) ** 2 <= r * r:
                    t.set(x, y, "g" if y < cy else "G")
    t.rect(0, 15, 16, 1, "G")
    return t.outline()

def flower():
    t = Canvas(16, 16)
    t.rect(7, 9, 1, 7, "G")
    t.set(6, 12, "g"); t.set(8, 11, "g")
    for dx, dy in ((0, -1), (-1, 0), (1, 0), (0, 1)):
        t.set(7 + dx, 7 + dy, "p")
    t.set(7, 7, "y")
    return t.outline()

def pole():
    t = Canvas(16, 16)
    t.rect(7, 0, 2, 16, "W")
    t.rect(8, 0, 1, 16, "m")
    return t.outline()

def flag_top():
    t = pole()
    t.rect(6, 0, 4, 2, "y")
    t.rect(9, 3, 6, 5, "g")
    t.rect(9, 4, 5, 3, "h")
    return t.outline()

def tuft():
    t = Canvas(16, 16)
    for x, h in ((3, 3), (5, 5), (7, 3), (10, 4), (12, 2)):
        t.rect(x, 16 - h, 1, h, "G" if x % 2 else "g")
    return t

def stone():
    t = Canvas(16, 16)
    t.rect(0, 0, 16, 16, "N")
    r = rnd(7)
    for _ in range(18):
        t.set(r(16), r(16), "n")
    return t

tiles = [grass_top(), dirt(3), brick(), plank(), spikes(), bonus(), bonus(True), bush(),
         flower(), pole(), flag_top(), tuft(), stone(), dirt(9), grass_top(), brick()]

# ----- Coin (4-frame spin), slime (2 walk + squashed), background ------------------
def coin(width):
    c = Canvas(16, 16)
    for y in range(3, 13):
        for x in range(16):
            dx = (x - 7.5) / max(0.5, width / 2)
            dy = (y - 7.5) / 5
            if dx * dx + dy * dy <= 1:
                c.set(x, y, "y")
    if width >= 4:
        c.rect(7, 5, 2, 6, "Y")
        c.set(6, 4, "o")
    return c.outline()

def slime(squash):
    c = Canvas(16, 16)
    h = [7, 6, 3][squash]
    w = [10, 12, 14][squash]
    top = 16 - h
    for y in range(top, 16):
        for x in range(16):
            nx = (x - 7.5) / (w / 2)
            ny = (y - 15.5) / h
            if nx * nx + ny * ny <= 1:
                c.set(x, y, "g" if y < top + h * 0.6 else "G")
    if squash < 2:
        c.set(6, top + 2, "k"); c.set(9, top + 2, "k")
        c.set(5, top + 1, "h")
    else:
        c.rect(5, top + 1, 2, 1, "k"); c.rect(9, top + 1, 2, 1, "k")
    return c.outline()

def hills():
    c = Canvas(128, 48)
    for x in range(128):
        h1 = 18 + 10 * math.sin(x / 128 * math.pi * 2) + 5 * math.sin(x / 20)
        h2 = 10 + 6 * math.sin(x / 128 * math.pi * 4 + 1)
        for y in range(48):
            if y > 48 - h1:
                c.set(x, y, "G" if y > 48 - h2 else "g")
    return c

def cloud():
    c = Canvas(32, 16)
    for cx, cy, r in ((9, 10, 5), (16, 7, 6), (23, 10, 5)):
        for y in range(16):
            for x in range(32):
                if (x - cx) ** 2 + (y - cy) ** 2 <= r * r:
                    c.set(x, y, "w" if y < 11 else "W")
    return c

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "assets", "sprites")
    sheet(player_frames, 9).save(os.path.join(out, "player.png"))
    sheet(tiles, 8).save(os.path.join(out, "tiles.png"))
    sheet([coin(10), coin(7), coin(2), coin(7)], 4).save(os.path.join(out, "coin.png"))
    sheet([slime(0), slime(1), slime(2)], 3).save(os.path.join(out, "slime.png"))
    hills().save(os.path.join(out, "hills.png"))
    cloud().save(os.path.join(out, "cloud.png"))
    print("wrote", os.path.normpath(out))
