// Agent team (docs/TEAM.md §7): the Team panel (roster with live state) and the agent profile
// dialog. Everything goes through the team.* commands, so an agent attached over MCP manages the
// team exactly as the person here does; the panel is hidden in tools that do not register them.
#include "editor/EditorInternal.h"
#include "editor/EditorText.h"

#include <algorithm>
#include <cfloat>
#include <cmath>
#include <cstring>

#include "imgui_internal.h"

#include "app/Engine.h"
#include "assets/Assets.h"
#include "core/FileSystem.h"
#include "core/Image.h"
#include "core/Log.h"
#include "render/GpuRenderer.h"
#include "render/Mesh.h"

namespace oe {

// Generated by CMakeLists.txt from engine/editor/avatars/*.png; ends with a null name.
struct EmbeddedAvatar {
    const char* name;
    const unsigned char* data;
    size_t size;
};
extern const EmbeddedAvatar kEmbeddedAvatars[];

bool EditorAvatarPreset(const std::string& name, const unsigned char** data, size_t* size) {
    for (const EmbeddedAvatar* avatar = kEmbeddedAvatars; avatar->name; ++avatar) {
        if (name != avatar->name) continue;
        if (data) *data = avatar->data;
        if (size) *size = avatar->size;
        return true;
    }
    return false;
}

namespace {

constexpr const char* kAgentPayload = "OE_AGENT";  // drag to reorder: agent id (char data)
constexpr size_t kMaxAvatarBytes = 16 * 1024 * 1024;
constexpr int kMaxAvatarPixels = 8192;

std::shared_ptr<const Texture> DecodeAvatar(const unsigned char* data, size_t size) {
    int width = 0, height = 0;
    if (!data || size == 0 || size > kMaxAvatarBytes || !ImageDimensions(data, size, width, height)) return nullptr;
    if (width > kMaxAvatarPixels || height > kMaxAvatarPixels) return nullptr;
    auto texture = std::make_shared<Texture>();
    std::string error;
    if (!DecodeImage(data, size, *texture, &error)) return nullptr;
    return texture;
}

// First character of a UTF-8 text (its bytes), for the letter on a picture-less avatar.
std::string FirstCharacter(const std::string& text) {
    if (text.empty()) return "?";
    size_t length = 1;
    while (length < text.size() && (static_cast<unsigned char>(text[length]) & 0xC0) == 0x80) ++length;
    return text.substr(0, length);
}

ImU32 StateColor(const std::string& state, double time) {
    // Running states pulse so a glance tells who is busy.
    const int pulse = 150 + static_cast<int>(105.0 * (0.5 + 0.5 * std::sin(time * 5.0)));
    if (state == "queued") return IM_COL32(90, 150, 240, 255);
    if (state == "thinking") return IM_COL32(240, 180, 60, pulse);
    if (state == "working") return IM_COL32(90, 210, 110, pulse);
    if (state == "error") return IM_COL32(230, 80, 80, 255);
    return IM_COL32(140, 145, 155, 255);  // idle, offline
}

std::string ElapsedText(double seconds) {
    const int total = static_cast<int>(seconds);
    return Format("%d:%02d", total / 60, total % 60);
}

}  // namespace

std::shared_ptr<const Texture> NativeEditor::Impl::AvatarTexture(const std::string& key) {
    const bool file = key.rfind("file:", 0) == 0;
    const std::string path = file ? key.substr(5) : std::string();
    const int64_t modified = file ? FileModifiedTime(path) : 0;
    auto found = avatarTextures.find(key);
    if (found != avatarTextures.end() && found->second.modified == modified) {
        found->second.lastUsed = time;
        return found->second.image;
    }
    if (avatarTextures.size() >= 64 && found == avatarTextures.end()) {
        avatarTextures.erase(std::min_element(avatarTextures.begin(), avatarTextures.end(),
                                              [](const auto& a, const auto& b) { return a.second.lastUsed < b.second.lastUsed; }));
    }
    AvatarImage& entry = avatarTextures[key];
    entry.modified = modified;
    entry.lastUsed = time;
    entry.image.reset();
    if (file) {
        std::vector<unsigned char> bytes;
        if (ReadBinaryFile(path, bytes)) entry.image = DecodeAvatar(bytes.data(), bytes.size());
    } else if (key.rfind("preset:", 0) == 0) {
        const unsigned char* data = nullptr;
        size_t size = 0;
        if (EditorAvatarPreset(key.substr(7), &data, &size)) entry.image = DecodeAvatar(data, size);
    }
    return entry.image;
}

// A round picture: the image center-cropped to a square, or a colored disc with the first
// letter of the name when there is none (unknown preset, unreadable file, no GPU texture).
void NativeEditor::Impl::DrawAvatar(ImDrawList* dl, ImVec2 pos, float size, const std::string& key, const std::string& id, const std::string& name) {
    const ImVec2 center(pos.x + size * 0.5f, pos.y + size * 0.5f);
    const std::shared_ptr<const Texture> image = AvatarTexture(key);
    if (image && image->width > 0 && image->height > 0 && engine.Gpu()) {
        const float w = static_cast<float>(image->width), h = static_cast<float>(image->height), side = std::min(w, h);
        const ImVec2 uv0((w - side) * 0.5f / w, (h - side) * 0.5f / h), uv1(1.0f - uv0.x, 1.0f - uv0.y);
        dl->AddImageRounded(ViewTexture(engine.Gpu()->ImageView(image)), pos, ImVec2(pos.x + size, pos.y + size), uv0, uv1, IM_COL32_WHITE, size * 0.5f);
        return;
    }
    const ImVec4 tint = ImGui::ColorConvertU32ToFloat4(AgentColor(id));
    dl->AddCircleFilled(center, size * 0.5f, ImGui::ColorConvertFloat4ToU32(ImVec4(tint.x * 0.72f, tint.y * 0.72f, tint.z * 0.72f, 1.0f)), 32);
    const std::string letter = FirstCharacter(name);
    const float fontSize = size * 0.55f;
    const ImVec2 extent = ImGui::GetFont()->CalcTextSizeA(fontSize, FLT_MAX, 0.0f, letter.c_str());
    dl->AddText(ImGui::GetFont(), fontSize, ImVec2(center.x - extent.x * 0.5f, center.y - extent.y * 0.5f), IM_COL32_WHITE, letter.c_str());
}

const Json* NativeEditor::Impl::TeamBackend(const std::string& id) const {
    for (const Json& backend : teamBackends.items()) {
        if (backend["id"].asString("") == id) return &backend;
    }
    return nullptr;
}

void NativeEditor::Impl::RefreshTeam() {
    const Json state = Call("team.state", Json(), true);
    if (!Ok(state)) return;
    teamState = state["result"];
    const double revision = teamState["revision"].asNumber(0.0);
    if (revision != teamListRevision) {
        const Json list = Call("team.list", Json(), true);
        if (Ok(list)) {
            team = list["result"];
            teamListRevision = revision;
        }
    }
    // CLI detection takes seconds: it runs in the background and is polled until it is done.
    bool detecting = teamBackends.size() == 0;
    for (const Json& backend : teamBackends.items()) detecting = detecting || backend["status"].asString("") == "detecting";
    if (detecting && time - teamBackendsPoll > 0.25) {
        teamBackendsPoll = time;
        const Json backends = Call("team.backends", ObjectOf({{"async", Json(true)}}), true);
        if (Ok(backends)) teamBackends = backends["result"];
    }
    if (teamPresets.size() == 0) teamPresets = Call("team.presets", Json(), true)["result"];
}

void NativeEditor::Impl::EditAgent(const std::string& id) {
    RefreshTeam();
    AgentForm form;
    form.isNew = id.empty();
    if (form.isNew) {
        // The first installed CLI (any, when none is: a team can be prepared before installing one).
        for (const Json& backend : teamBackends.items()) {
            if (form.backend.empty() || (backend["status"].asString("") == "installed" && !form.installed)) {
                form.backend = backend["id"].asString("");
                form.installed = backend["status"].asString("") == "installed";
            }
        }
        if (const Json* backend = TeamBackend(form.backend)) {
            for (const Json& model : (*backend)["models"].items()) {
                if (model["default"].asBool(false)) form.model = model["id"].asString("");
            }
        }
        // The first picture no teammate uses yet, as team.add would choose.
        for (const Json& preset : teamPresets.items()) {
            const std::string avatar = "preset:" + preset.asString("");
            bool used = false;
            for (const Json& agent : team["agents"].items()) used = used || agent["avatar"].asString("") == avatar;
            if (form.avatar.empty() || !used) form.avatar = avatar;
            if (!used) break;
        }
    } else {
        const Json agent = Call("team.get", ObjectOf({{"id", Json(id)}}))["result"];
        if (!agent.isObject()) return;
        form.id = agent["id"].asString("");
        form.name = agent["name"].asString("");
        form.description = agent["description"].asString("");
        form.instructions = agent["instructions"].asString("");
        form.backend = agent["backend"].asString("");
        form.model = agent["model"].asString("");
        form.access = agent["access"].asString("edit");
        form.avatar = agent["avatar"].asString("");
        form.avatarPath = agent["avatarPath"].asString("");
        if (const Json* backend = TeamBackend(form.backend)) {
            form.customModel = !form.model.empty();
            for (const Json& model : (*backend)["models"].items()) form.customModel = form.customModel && model["id"].asString("") != form.model;
        }
    }
    form.originalAvatar = form.avatar;
    agentForm = form;
    openAgentDialog = true;
}

bool NativeEditor::Impl::SetAgentFormBackend(const std::string& id) {
    const Json* backend = TeamBackend(id);
    if (!backend || (*backend)["status"].asString("") != "installed") return false;  // a CLI that is not on this PC cannot be chosen
    if (agentForm.backend == id) return true;
    agentForm.backend = id;
    agentForm.model.clear();
    agentForm.customModel = false;
    for (const Json& model : (*backend)["models"].items()) {
        if (model["default"].asBool(false)) agentForm.model = model["id"].asString("");
    }
    return true;
}

// team.add / team.update (+ team.avatar for an uploaded picture). False keeps the dialog open
// with the command's message.
bool NativeEditor::Impl::SaveAgentForm() {
    AgentForm& form = agentForm;
    Json values = Json::MakeObject();
    values["name"] = form.name;
    values["description"] = form.description;
    values["instructions"] = form.instructions;
    values["backend"] = form.backend;
    values["model"] = form.model;
    values["access"] = form.access;
    if (form.avatarSource.empty() && form.avatar.rfind("preset:", 0) == 0 && (form.isNew || form.avatar != form.originalAvatar)) values["avatar"] = form.avatar;
    auto failed = [&](const Json& response) {
        if (Ok(response)) return false;
        form.error = response["error"]["message"].asString("failed");
        if (!response["error"]["hint"].asString("").empty()) form.error += "\n" + response["error"]["hint"].asString();
        return true;
    };
    const Json saved = form.isNew ? Call("team.add", values, true) : Call("team.update", ObjectOf({{"id", Json(form.id)}, {"values", values}}), true);
    if (failed(saved)) return false;
    form.id = saved["result"]["id"].asString("");
    form.isNew = false;  // the agent exists now, whatever happens to its picture
    form.originalAvatar = saved["result"]["avatar"].asString("");
    teamListRevision = -1;
    selectedAgent = form.id;
    if (!form.avatarSource.empty() && failed(Call("team.avatar", ObjectOf({{"id", Json(form.id)}, {"source", Json(form.avatarSource)}}), true))) return false;
    form.error.clear();
    return true;
}

void NativeEditor::Impl::TeamPanel() {
    if (requestTeamFocus) {
        ImGui::SetNextWindowFocus();
        requestTeamFocus = false;
    }
    if (!ImGui::Begin(TrId("Team").c_str(), &showTeam)) {
        ImGui::End();
        return;
    }
    const Json& agents = team["agents"];
    if (ImGui::Button(Tr("Add Agent"))) EditAgent("");
    if (team.has("error")) {
        ImGui::PushStyleColor(ImGuiCol_Text, IM_COL32(240, 110, 110, 255));
        ImGui::TextWrapped("%s", team["error"].asString("").c_str());
        ImGui::PopStyleColor();
    }
    if (agents.size() == 0 && !team.has("error")) {
        ImGui::Spacing();
        ImGui::TextWrapped("%s", Tr("Agents work through the coding-agent CLIs installed on this PC (Claude Code, Codex)."));
        ImGui::Spacing();
        if (ImGui::Button(Tr("Add your first agent"))) EditAgent("");
    }
    ImGui::Separator();

    const ImGuiStyle& style = ImGui::GetStyle();
    const float line = ImGui::GetTextLineHeight();
    const float rowHeight = line * 2.0f + style.ItemSpacing.y, avatarSize = rowHeight - 2.0f;
    const ImU32 textColor = ImGui::GetColorU32(ImGuiCol_Text), dimColor = ImGui::GetColorU32(ImGuiCol_TextDisabled);
    const std::string lead = team["lead"].asString("");
    ImDrawList* dl = ImGui::GetWindowDrawList();
    int index = 0;
    std::string moveId;
    int moveIndex = -1;
    for (const Json& agent : agents.items()) {
        const std::string id = agent["id"].asString(""), name = agent["name"].asString("");
        Json liveState;
        for (const Json& entry : teamState["agents"].items()) {
            if (entry["id"].asString("") == id) liveState = entry;
        }
        const Json& live = liveState;
        const std::string state = live["state"].asString("idle");
        const bool busy = state == "thinking" || state == "working" || state == "queued";
        ImGui::PushID(id.c_str());
        const ImVec2 pos = ImGui::GetCursorScreenPos();
        const float rowWidth = ImGui::GetContentRegionAvail().x;
        if (ImGui::Selectable("##agent", selectedAgent == id, ImGuiSelectableFlags_AllowDoubleClick | ImGuiSelectableFlags_AllowOverlap, ImVec2(0, rowHeight))) {
            selectedAgent = id;
            // Selecting an agent addresses the chat to it, unless the person already typed something.
            if (chatInput.empty() || chatInput == chatAutoMention) chatInput = chatAutoMention = "@" + id + " ";
            if (ImGui::IsMouseDoubleClicked(ImGuiMouseButton_Left)) EditAgent(id);
        }
        if (ImGui::IsItemHovered(ImGuiHoveredFlags_DelayNormal)) {
            std::string tip = agent["description"].asString("");
            if (!live["error"].asString("").empty()) tip += (tip.empty() ? "" : "\n\n") + live["error"].asString("");
            if (!live["hint"].asString("").empty()) tip += "\n" + live["hint"].asString("");
            if (!tip.empty()) {
                ImGui::BeginTooltip();
                ImGui::PushTextWrapPos(ImGui::GetFontSize() * 30.0f);
                ImGui::TextUnformatted(tip.c_str());
                ImGui::PopTextWrapPos();
                ImGui::EndTooltip();
            }
        }
        if (ImGui::BeginDragDropSource(ImGuiDragDropFlags_SourceNoHoldToOpenOthers)) {
            ImGui::SetDragDropPayload(kAgentPayload, id.c_str(), id.size() + 1);
            ImGui::TextUnformatted(name.c_str());
            ImGui::EndDragDropSource();
        }
        if (ImGui::BeginDragDropTarget()) {
            if (const ImGuiPayload* payload = ImGui::AcceptDragDropPayload(kAgentPayload)) {
                moveId = static_cast<const char*>(payload->Data);
                moveIndex = index;
            }
            ImGui::EndDragDropTarget();
        }
        if (ImGui::BeginPopupContextItem("##menu")) {
            selectedAgent = id;
            if (ImGui::MenuItem(Tr("Edit"))) EditAgent(id);
            if (ImGui::MenuItem(Tr("Make Lead"), nullptr, false, lead != id)) Call("team.settings", ObjectOf({{"lead", Json(id)}}));
            if (ImGui::MenuItem(Tr("Stop"), nullptr, false, busy)) Call("team.cancel", ObjectOf({{"id", Json(id)}}));
            ImGui::Separator();
            if (ImGui::MenuItem(Tr("Delete"))) {
                removeAgentId = id;
                openRemoveAgent = true;
            }
            ImGui::EndPopup();
        }

        // Picture with the status dot at its lower right.
        const ImVec2 avatarPos(pos.x + 2.0f, pos.y + 1.0f);
        DrawAvatar(dl, avatarPos, avatarSize, agent["avatar"].asString("") == "file" ? "file:" + JoinPath(engine.ProjectDir(), agent["avatarPath"].asString("")) : agent["avatar"].asString(""), id, name);
        const float dot = std::max(3.0f, avatarSize * 0.17f);
        const ImVec2 dotCenter(avatarPos.x + avatarSize - dot, avatarPos.y + avatarSize - dot);
        dl->AddCircleFilled(dotCenter, dot + 1.5f, ImGui::GetColorU32(ImGuiCol_WindowBg));
        if (state == "offline") dl->AddCircle(dotCenter, dot - 0.5f, StateColor(state, time), 0, 1.5f);
        else dl->AddCircleFilled(dotCenter, dot, StateColor(state, time));

        // Line 1: name (lead mark), backend and model. Line 2: what the agent is doing.
        const float textX = avatarPos.x + avatarSize + style.ItemSpacing.x;
        const Json* backend = TeamBackend(agent["backend"].asString(""));
        const std::string model = agent["model"].asString("");
        const std::string engineText = (backend ? (*backend)["name"].asString("") : agent["backend"].asString("")) + " \xC2\xB7 " + (model.empty() ? std::string(Tr("CLI default")) : model);
        std::string status = state == "offline" ? Tr("Offline") : state == "queued" ? Tr("Queued") : state == "error" ? Tr("Error") : state == "thinking" ? Tr("Thinking") :
                             state == "working" ? live["activity"].asString("") : Tr("Idle");
        const bool running = state == "thinking" || state == "working";
        const std::string stopLabel = Tr("Stop");
        const float stopWidth = running ? ImGui::CalcTextSize(stopLabel.c_str()).x + style.FramePadding.x * 2.0f + style.ItemSpacing.x : 0.0f;
        const std::string elapsed = running ? ElapsedText(live["elapsed"].asNumber(0.0)) : std::string();
        const float elapsedWidth = running ? ImGui::CalcTextSize(elapsed.c_str()).x + style.ItemSpacing.x : 0.0f;
        dl->PushClipRect(ImVec2(textX, pos.y), ImVec2(pos.x + rowWidth, pos.y + rowHeight), true);
        dl->AddText(ImVec2(textX, pos.y + 1.0f), textColor, name.c_str());
        float after = textX + ImGui::CalcTextSize(name.c_str()).x + style.ItemSpacing.x;
        if (lead == id) {
            dl->AddText(ImVec2(after, pos.y + 1.0f), IM_COL32(240, 200, 90, 255), Tr("Lead"));
            after += ImGui::CalcTextSize(Tr("Lead")).x + style.ItemSpacing.x;
        }
        dl->AddText(ImVec2(after, pos.y + 1.0f), dimColor, engineText.c_str());
        dl->PopClipRect();
        dl->PushClipRect(ImVec2(textX, pos.y), ImVec2(pos.x + rowWidth - stopWidth - elapsedWidth, pos.y + rowHeight), true);
        dl->AddText(ImVec2(textX, pos.y + 1.0f + line + style.ItemSpacing.y * 0.5f), state == "error" ? IM_COL32(240, 110, 110, 255) : dimColor, status.c_str());
        dl->PopClipRect();
        if (running) {
            dl->AddText(ImVec2(pos.x + rowWidth - stopWidth - elapsedWidth + style.ItemSpacing.x * 0.5f, pos.y + 1.0f + line + style.ItemSpacing.y * 0.5f), dimColor, elapsed.c_str());
            // On the row's line (the row allows overlap), pushed down to the second text line.
            ImGui::SameLine(pos.x + rowWidth - stopWidth + style.ItemSpacing.x - ImGui::GetWindowPos().x + ImGui::GetScrollX());
            ImGui::SetCursorPosY(ImGui::GetCursorPosY() + line + style.ItemSpacing.y * 0.5f - 1.0f);
            if (ImGui::SmallButton(stopLabel.c_str())) Call("team.cancel", ObjectOf({{"id", Json(id)}}));
        }
        ImGui::PopID();
        ++index;
    }
    if (moveIndex >= 0) {
        Call("team.move", ObjectOf({{"id", Json(moveId)}, {"index", Json(moveIndex)}}));
        teamListRevision = -1;
    }
    ImGui::End();
}

void NativeEditor::Impl::TeamModals() {
    AgentForm& form = agentForm;
    if (openAgentDialog) {
        ImGui::OpenPopup(TrId("Agent").c_str());
        openAgentDialog = false;
    }
    if (openRemoveAgent) {
        ImGui::OpenPopup(TrId("Remove Agent").c_str());
        openRemoveAgent = false;
    }
    const ImVec2 center = ImGui::GetMainViewport()->GetCenter();
    const float font = ImGui::GetFontSize(), labelWidth = font * 7.0f, fieldWidth = font * 22.0f, buttonWidth = font * 6.0f;

    ImGui::SetNextWindowPos(center, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
    if (ImGui::BeginPopupModal(TrId("Agent").c_str(), nullptr, ImGuiWindowFlags_AlwaysAutoResize)) {
        const Json* backend = TeamBackend(form.backend);
        const bool installed = backend && (*backend)["status"].asString("") == "installed";
        bool save = false, anyInstalled = false, detecting = false;
        for (const Json& item : teamBackends.items()) {
            anyInstalled = anyInstalled || item["status"].asString("") == "installed";
            detecting = detecting || item["status"].asString("") == "detecting";
        }

        // Picture and its picker on the left, fields on the right.
        const float avatarSize = font * 4.0f;
        ImGui::BeginGroup();
        const ImVec2 avatarPos = ImGui::GetCursorScreenPos();
        ImGui::Dummy(ImVec2(avatarSize, avatarSize));
        const std::string avatarKey = !form.avatarSource.empty() ? "file:" + form.avatarSource :
                                      form.avatar == "file" ? "file:" + JoinPath(engine.ProjectDir(), form.avatarPath) : form.avatar;
        DrawAvatar(ImGui::GetWindowDrawList(), avatarPos, avatarSize, avatarKey, form.id.empty() ? form.name : form.id, form.name);
        if (ImGui::Button(Tr("Change"), ImVec2(avatarSize, 0))) ImGui::OpenPopup("##avatar");
        if (ImGui::BeginPopup("##avatar")) {
            int column = 0;
            for (const Json& preset : teamPresets.items()) {
                const std::string key = "preset:" + preset.asString("");
                if (column++ % 4 != 0) ImGui::SameLine();
                const ImVec2 at = ImGui::GetCursorScreenPos();
                ImGui::PushID(key.c_str());
                if (ImGui::InvisibleButton("##preset", ImVec2(font * 3.0f, font * 3.0f))) {
                    form.avatar = key;
                    form.avatarSource.clear();
                    ImGui::CloseCurrentPopup();
                }
                DrawAvatar(ImGui::GetWindowDrawList(), at, font * 3.0f, key, key, preset.asString(""));
                if (ImGui::IsItemHovered() || (form.avatarSource.empty() && form.avatar == key)) {
                    ImGui::GetWindowDrawList()->AddCircle(ImVec2(at.x + font * 1.5f, at.y + font * 1.5f), font * 1.5f, ImGui::GetColorU32(ImGuiCol_ButtonActive), 32, 2.0f);
                }
                ImGui::PopID();
            }
            if (ImGui::Button(Tr("Upload..."))) {
                FileDialogOptions request;
                request.title = Tr("Upload...");
                request.pattern = "*.png;*.jpg;*.jpeg";
                const FileDialogResult result = window ? window->ChooseFile(request) : FileDialogResult{};
                if (result.status == FileDialogResult::Status::Selected) {
                    form.avatarSource = result.path;
                    ImGui::CloseCurrentPopup();
                } else if (result.status == FileDialogResult::Status::Unavailable) {
                    form.showPathInput = true;  // no native dialog here: type the path
                } else if (result.status == FileDialogResult::Status::Error) {
                    form.error = result.error;
                }
            }
            if (form.showPathInput) {
                ImGui::TextUnformatted(Tr("Image file path (png, jpg):"));
                ImGui::SetNextItemWidth(font * 18.0f);
                const bool enter = ImGui::InputText("##avatarPath", &form.pathInput, ImGuiInputTextFlags_EnterReturnsTrue);
                ImGui::SameLine();
                if ((ImGui::Button(Tr("Apply")) || enter) && !form.pathInput.empty()) {
                    form.avatarSource = form.pathInput;
                    ImGui::CloseCurrentPopup();
                }
            }
            ImGui::EndPopup();
        }
        ImGui::EndGroup();
        ImGui::SameLine(0.0f, font);

        ImGui::BeginGroup();
        auto label = [&](const char* text) {
            ImGui::AlignTextToFramePadding();
            ImGui::TextUnformatted(text);
            ImGui::SameLine(labelWidth);
            ImGui::SetNextItemWidth(fieldWidth);
        };
        label(Tr("Name"));
        if (ImGui::IsWindowAppearing()) ImGui::SetKeyboardFocusHere();
        save = ImGui::InputText("##name", &form.name, ImGuiInputTextFlags_EnterReturnsTrue);
        label(Tr("Description"));
        ImGui::InputText("##description", &form.description);

        label(Tr("Agent"));
        if (ImGui::BeginCombo("##backend", backend ? (*backend)["name"].asString("").c_str() : form.backend.c_str())) {
            for (const Json& item : teamBackends.items()) {
                const std::string status = item["status"].asString(""), id = item["id"].asString("");
                const bool selectable = status == "installed";
                const std::string text = item["name"].asString("") + "  " +
                                         (selectable ? item["version"].asString("") : status == "detecting" ? std::string(Tr("(checking...)")) :
                                          status == "notInstalled" ? std::string(Tr("(not installed)")) : std::string(Tr("(not working)")));
                if (ImGui::Selectable(text.c_str(), form.backend == id, selectable ? ImGuiSelectableFlags_None : ImGuiSelectableFlags_Disabled)) SetAgentFormBackend(id);
                if (!selectable) HelpTooltip(item["message"].asString("") + "\n" + item["installHint"].asString(""));
            }
            ImGui::EndCombo();
        }

        label(Tr("Model"));
        ImGui::BeginDisabled(!installed);
        std::string modelLabel = form.customModel ? std::string(Tr("Custom...")) : form.model.empty() ? std::string(Tr("CLI default")) : form.model;
        if (backend && !form.customModel) {
            for (const Json& model : (*backend)["models"].items()) {
                if (model["id"].asString("") == form.model) modelLabel = model["label"].asString(form.model);
            }
        }
        if (ImGui::BeginCombo("##model", modelLabel.c_str())) {
            if (ImGui::Selectable(Tr("CLI default"), !form.customModel && form.model.empty())) {
                form.model.clear();
                form.customModel = false;
            }
            if (backend) {
                for (const Json& model : (*backend)["models"].items()) {
                    const std::string id = model["id"].asString("");
                    if (ImGui::Selectable((model["label"].asString(id) + "##" + id).c_str(), !form.customModel && form.model == id)) {
                        form.model = id;
                        form.customModel = false;
                    }
                }
            }
            if (ImGui::Selectable(Tr("Custom..."), form.customModel)) form.customModel = true;
            ImGui::EndCombo();
        }
        if (form.customModel) {
            label("");
            ImGui::InputText("##customModel", &form.model);
        }
        ImGui::EndDisabled();

        label(Tr("Access"));
        const char* accessIds[] = {"read", "edit", "full"};
        const char* accessLabels[] = {Tr("Read only"), Tr("Edit project"), Tr("Full access")};
        int access = form.access == "read" ? 0 : form.access == "full" ? 2 : 1;
        if (ImGui::BeginCombo("##access", accessLabels[access])) {
            for (int i = 0; i < 3; ++i) {
                if (!ImGui::Selectable(accessLabels[i], access == i) || access == i) continue;
                if (i == 2) form.askFull = true;  // asked first, once the combo has closed
                else form.access = accessIds[i];
            }
            ImGui::EndCombo();
        }
        ImGui::EndGroup();
        if (form.askFull) {
            ImGui::OpenPopup(TrId("Allow Full Access").c_str());
            form.askFull = false;
        }
        ImGui::SetNextWindowPos(center, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
        if (ImGui::BeginPopupModal(TrId("Allow Full Access").c_str(), nullptr, ImGuiWindowFlags_AlwaysAutoResize)) {
            ImGui::PushTextWrapPos(font * 26.0f);
            ImGui::TextUnformatted(Tr("Full access lets the agent run any command on this PC without asking."));
            ImGui::PopTextWrapPos();
            ImGui::Spacing();
            if (ImGui::Button(Tr("Allow"), ImVec2(buttonWidth, 0))) {
                form.access = "full";
                ImGui::CloseCurrentPopup();
            }
            ImGui::SameLine();
            if (ImGui::Button(Tr("Cancel"), ImVec2(buttonWidth, 0)) || ImGui::IsKeyPressed(ImGuiKey_Escape)) ImGui::CloseCurrentPopup();
            ImGui::EndPopup();
        }

        ImGui::TextUnformatted(Tr("Instructions"));
        ImGui::InputTextMultiline("##instructions", &form.instructions, ImVec2(avatarSize + font + labelWidth + fieldWidth, ImGui::GetTextLineHeight() * 8.0f));
        if (!anyInstalled && !detecting) {
            ImGui::PushTextWrapPos(ImGui::GetCursorPosX() + avatarSize + font + labelWidth + fieldWidth);
            ImGui::TextDisabled("%s", Tr("No agent CLI is installed. Install Claude Code or Codex, then press Refresh agents."));
            ImGui::PopTextWrapPos();
        }
        if (!form.error.empty()) {
            ImGui::PushStyleColor(ImGuiCol_Text, IM_COL32(240, 110, 110, 255));
            ImGui::PushTextWrapPos(ImGui::GetCursorPosX() + avatarSize + font + labelWidth + fieldWidth);
            ImGui::TextUnformatted(form.error.c_str());
            ImGui::PopTextWrapPos();
            ImGui::PopStyleColor();
        }
        ImGui::Spacing();
        if (ImGui::Button(Tr("Refresh agents"))) {
            const Json refreshed = Call("team.backends", ObjectOf({{"refresh", Json(true)}, {"async", Json(true)}}), true);
            if (Ok(refreshed)) teamBackends = refreshed["result"];
        }
        ImGui::SameLine();
        ImGui::Dummy(ImVec2(font, 0));
        ImGui::SameLine();
        // Escape closes the innermost thing only: this dialog when no popup of its own is open.
        const bool topmost = ImGui::GetTopMostPopupModal() == ImGui::GetCurrentWindow() && !ImGui::IsPopupOpen("##avatar");
        if (ImGui::Button(Tr("Cancel"), ImVec2(buttonWidth, 0)) || (topmost && ImGui::IsKeyPressed(ImGuiKey_Escape))) ImGui::CloseCurrentPopup();
        ImGui::SameLine();
        if ((ImGui::Button(Tr("Save"), ImVec2(buttonWidth, 0)) || save) && SaveAgentForm()) ImGui::CloseCurrentPopup();
        ImGui::EndPopup();
    }

    ImGui::SetNextWindowPos(center, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
    if (ImGui::BeginPopupModal(TrId("Remove Agent").c_str(), nullptr, ImGuiWindowFlags_AlwaysAutoResize)) {
        std::string name = removeAgentId;
        for (const Json& agent : team["agents"].items()) {
            if (agent["id"].asString("") == removeAgentId) name = agent["name"].asString("");
        }
        ImGui::Text(Tr("Delete agent \"%s\"?"), name.c_str());
        ImGui::TextDisabled("%s", Tr("The chat history is kept."));
        ImGui::Spacing();
        if (ImGui::Button(Tr("Delete"), ImVec2(buttonWidth, 0)) || ImGui::IsKeyPressed(ImGuiKey_Enter)) {
            Call("team.remove", ObjectOf({{"id", Json(removeAgentId)}}));
            if (selectedAgent == removeAgentId) selectedAgent.clear();
            teamListRevision = -1;
            ImGui::CloseCurrentPopup();
        }
        ImGui::SameLine();
        if (ImGui::Button(Tr("Cancel"), ImVec2(buttonWidth, 0)) || ImGui::IsKeyPressed(ImGuiKey_Escape)) ImGui::CloseCurrentPopup();
        ImGui::EndPopup();
    }
}

void NativeEditor::FocusTeamPanel() { impl_->showTeam = impl_->requestTeamFocus = true; }
void NativeEditor::EditAgent(const std::string& id) {
    if (impl_->teamAvailable) impl_->EditAgent(id);
}
bool NativeEditor::SetAgentBackend(const std::string& backend) { return impl_->SetAgentFormBackend(backend); }
void NativeEditor::RemoveAgent(const std::string& id) {
    impl_->removeAgentId = id;
    impl_->openRemoveAgent = impl_->teamAvailable;
}

}  // namespace oe
